name: Deploy to static server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to static server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm run build

      - name: upload files
        uses: fangbinwei/aliyun-oss-website-action@v1.4.1
        with:
          accessKeyId: ${{ secrets.ACCESSKEY_ID }}
          accessKeySecret: ${{ secrets.ACCESSKEY_SECRET }}
          bucket: web-new-toiletmc
          endpoint: oss-cn-hangzhou.aliyuncs.com
          folder: ./dist
